# Generated by Django 5.0.2 on 2024-02-13 01:38

import audioclip.models
import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=512, populate_from=['title'], unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('audio', models.FileField(upload_to=audioclip.models.user_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audioclips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AudioClip',
                'verbose_name_plural': 'AudioClips',
                'ordering': ('-created_at', 'title'),
                'unique_together': {('user', 'title')},
            },
        ),
    ]
