# Generated by Django 5.0.2 on 2024-02-13 20:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioclip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioclip',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
