# Generated by Django 5.0.2 on 2024-02-15 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioclip', '0002_audioclip_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioclip',
            name='transcription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
