# Generated by Django 5.0.2 on 2024-02-15 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioclip', '0004_alter_audioclip_transcription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioclip',
            name='transcription',
            field=models.JSONField(default=dict),
        ),
    ]
