# Generated by Django 5.0.2 on 2024-02-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioclip', '0005_alter_audioclip_transcription'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioclip',
            name='ai_prompts',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='audioclip',
            name='transcribed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audioclip',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='audioclip',
            name='transcription',
            field=models.TextField(blank=True, default=''),
        ),
    ]
