# Generated by Django 5.0.2 on 2024-02-16 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioclip', '0006_audioclip_ai_prompts_audioclip_transcribed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioclip',
            name='is_transcribed',
            field=models.BooleanField(default=False),
        ),
    ]
