# Generated by Django 5.0.2 on 2024-02-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioclip', '0007_audioclip_is_transcribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioclip',
            name='ai_prompts',
            field=models.JSONField(default=list),
        ),
    ]
