version: "3.8"

services:
  # an-frontend:
  #   build: ./frontend/
  #   container_name: an-frontend
  #   entrypoint: /frontend/dev.entrypoint.sh
  #   volumes:
  #     - ./frontend:/frontend
  #     - node_modules:/frontend/node_modules
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - staging
  #   depends_on:
  #     - an-backend
  an-backend:
    build:
      context: ./backend/
      dockerfile: dev.Dockerfile
    container_name: an-backend
    entrypoint: /backend/dev.entrypoint.sh
    volumes:
      - ./backend:/backend
      - static:/backend/static
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"
    env_file:
      - ./backend/dev.env
    networks:
      - staging
    depends_on:
      - an-redis
      # - an-db
  # an-db:
  #   image: postgres:alpine
  #   container_name: an-db
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_USER=an-admin
  #     - POSTGRES_PASSWORD=an-admin
  #     - POSTGRES_DB=audionimbus
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  #   networks:
  #     - staging
  an-redis:
    image: redis:latest
    container_name: an-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - staging

volumes:
  static:
  # node_modules:
  db_data:
  redis_data:


networks:
  staging:
    driver: bridge
    ipam:
      config:
        - subnet: 134.28.0.0/16
          gateway: 134.28.0.1
